---
  - name: Disable Auto Updates
    win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
      name: NoAutoUpdate
      data: 1
      type: dword
      state: present