---
- hosts: tien
  gather_facts: True
  vars:
    ansible_winrm_transport: plaintext
    ansible_winrm_scheme: http
    capsulecorp_domain_hostname: "tien"
    host_ip: "10.0.1.7"
    dns_server: "10.0.1.2"
    ethernet_adapter: "Local Area Connection"
    anpt_flag: "flag2.txt"
  roles:
   - role: disable_au
   - role: placeflag
   - role: local_admin
   - role: windows_ip
   - role: joindomain