---
- name: Install cUrl
  win_chocolatey:
     name: curl
     state: present
     
- name: Install Jenkins
  win_chocolatey:
    name: jenkins
    state: present
  register: jenkins_install_package_win

