---
- name: Bypass the security wizard
  template:
    src: jenkins.lastExecVersion
    dest: "{{ jenkins_home }}/jenkins.install.InstallUtil.lastExecVersion"
  register: jenkins_init

- name: Add agruments in init file
  win_lineinfile:
    path: "{{ jenkins_init_file }}"
    backrefs: yes
    regexp: '(<arguments>)(.*)(</arguments>)'
    line: '$1{{ jenkins_wrapper_options }} $2$3'
  register: jenkins_init_args

- name: Create custom init scripts directory.
  win_file:
    path: "{{ jenkins_home }}/init.groovy.d"
    state: directory

- name: Configure Jenkins default users.
  template:
    src: basic-security.groovy
    dest: "{{ jenkins_home }}/init.groovy.d/basic-security.groovy"
  register: jenkins_users_config
  when: (jenkins_install_package_win is defined and jenkins_install_package_win.changed)

- name: Set JNLP port for CLI access
  template:
    src: set_jnlp_port.groovy
    dest: "{{ jenkins_home }}/init.groovy.d/set_jnlp_port.groovy"
  register: jenkins_jnlp_port_config
  when: (jenkins_install_package_win is defined and jenkins_install_package_win.changed)

- name: Immediately restart Jenkins after all changes.
  win_service: name=jenkins state=restarted
  register: jenkins_started

- name: Remove Jenkins security init scripts after first startup.
  win_file:
    path: "{{ jenkins_home }}/init.groovy.d/basic-security.groovy"
    state: absent
  when: jenkins_started is defined
