---
- name: Ensure cUrl is installed.
  win_chocolatey:
     name: curl
     state: present

- name: Ensure Java RE is installed
  win_chocolatey:
     name: jre8
     state: present

- name: Ensure Tomcat is installed.
  win_chocolatey:
     name: tomcat
     version: 9.0.30
     state: present
  register: tomcat_installed

- name: Set the insecure tomcat-users.xml file in the right place
  template:
    src: tomcat-users.xml
    dest: "C:\\ProgramData\\Tomcat9\\conf\\tomcat-users.xml"
  register: tomcat_users
  when: tomcat_installed.changed

- name: Set the server.xml file with AJP enabled
  template:
    src: server.xml
    dest: "C:\\ProgramData\\Tomcat9\\conf\\server.xml"
  register: tomcat_server_conf
  when: tomcat_installed.changed

- name: Allow access to manager gui from anywhere
  template:
    src: context.xml
    dest: "C:\\ProgramData\\Tomcat9\\webapps\\manager\\META-INF\\context.xml"
  register: tomcat_context
  when: tomcat_installed.changed
     
- name: Configure service to run as system
  win_service:
    name: Tomcat9
    start_mode: auto
    username: LocalSystem
    password: ""
    state: restarted
  when: tomcat_installed.changed
    
- include: firewall_8080.yml
  when: tomcat_installed.changed

- include: firewall_8009.yml
  when: tomcat_installed.changed


