---
  - name: Change root password
    user:
      name: "root"
      state: present
      password: "$6$9OygqSYpI3E1heYI$O/TRK7klFR7bgkoaXFtFoY59zQV.ZGspKUhHIEbGGYC2PrRhGmOeR3.rJyncSdzjrOdC038zmUFSZlwvGAjQC/" # P@ssW0rd123#_!

  - name: Create user piccolo
    shell: useradd -m piccolo; chsh -s /bin/bash piccolo

  - name: Change piccolo password
    user:
      name: "piccolo"
      state: present
      password: "$6$kdihQS/ELHVfbp2Q$OEmTEusT5uUfhZW7QpjHMasH92UKhZ0kp7Fc1gOw.aMogCFho9LPDvDdBANXJpCBRICKzwLTX7asztvxlYvfl0" # P@ssW0rd123#

  - name: Add SUID bit to /usr/bin/cp
    shell: chmod u+s /usr/bin/cp 

  - name: Upload Interfaces
    template:
      src: "files/01-netcfg.yaml"
      dest: "/etc/netplan/01-netcfg.yaml"

  - name: Netplan apply
    command: netplan apply
    async: 1
    poll: 0

  - name: Add host with new IP address
    add_host:
      name: "{{ inventory_hostname }}"
      ansible_host: "{{host_ip}}"

  - name: Wait for connections
    wait_for_connection: