---
  - name: Piccolo | Upload Interfaces
    template:
      src: "files/01-netcfg.yaml"
      dest: "/etc/netplan/01-netcfg.yaml"

  - name: Piccolo | Reboot the machine
    reboot:
      reboot_timeout: 100