---
  - name: Kali | Install "python3-impacket" package
    ansible.builtin.apt:
      name: python3-impacket
      update_cache: yes

  - name: Kali | Install "remmina" package
    ansible.builtin.apt:
      name: remmina

  - name: Kali | Upload Interfaces
    template:
      src: "files/interfaces"
      dest: "/etc/network/interfaces"
      
  - name: Kali | Upload Wired Connection 1
    template:
      src: "files/WiredConnection1"
      dest: "/etc/NetworkManager/system-connections/Wired\ connection\ 1"

  - name: Kali | Reboot the machine
    reboot:
      reboot_timeout: 100